// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: itda/poa/v1/poa.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters of the Proof-of-Authority module.
type Params struct {
	// max_validators is the maximum number of validators allowed in the active
	// set. Adding a validator beyond this limit is rejected.
	MaxValidators uint32 `protobuf:"varint,1,opt,name=max_validators,json=maxValidators,proto3" json:"max_validators,omitempty"`
	// default_power is the consensus voting power assigned to a validator when
	// MsgAddValidator does not specify one explicitly.
	DefaultPower int64 `protobuf:"varint,2,opt,name=default_power,json=defaultPower,proto3" json:"default_power,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6fef0b0ad966260, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxValidators() uint32 {
	if m != nil {
		return m.MaxValidators
	}
	return 0
}

func (m *Params) GetDefaultPower() int64 {
	if m != nil {
		return m.DefaultPower
	}
	return 0
}

// Validator is a single authority-approved consensus node.
type Validator struct {
	// operator_address is the bech32 account address that controls this
	// validator entry. It is the primary key of the validator set.
	OperatorAddress string `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	// consensus_pubkey is the public key CometBFT uses to identify this node
	// when signing blocks. Must implement cosmos.crypto.PubKey.
	ConsensusPubkey *types.Any `protobuf:"bytes,2,opt,name=consensus_pubkey,json=consensusPubkey,proto3" json:"consensus_pubkey,omitempty"`
	// moniker is a human-readable label for operators and explorers.
	Moniker string `protobuf:"bytes,3,opt,name=moniker,proto3" json:"moniker,omitempty"`
	// power is the consensus voting power handed to CometBFT. Under pure PoA
	// this is typically 1 for every validator, giving each authority an equal
	// vote, but unequal weights are permitted.
	Power int64 `protobuf:"varint,4,opt,name=power,proto3" json:"power,omitempty"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6fef0b0ad966260, []int{1}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return m.Size()
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *Validator) GetConsensusPubkey() *types.Any {
	if m != nil {
		return m.ConsensusPubkey
	}
	return nil
}

func (m *Validator) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *Validator) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "itda.poa.v1.Params")
	proto.RegisterType((*Validator)(nil), "itda.poa.v1.Validator")
}

func init() { proto.RegisterFile("itda/poa/v1/poa.proto", fileDescriptor_b6fef0b0ad966260) }

var fileDescriptor_b6fef0b0ad966260 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x50, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x69, 0x29, 0xea, 0x96, 0xd0, 0xd6, 0x0a, 0x92, 0xc9, 0xc1, 0x54, 0x45, 0x48, 0x15,
	0x92, 0xbd, 0x2a, 0xdc, 0x2a, 0x2e, 0x09, 0x5c, 0x10, 0x12, 0xb2, 0x5c, 0xa9, 0x12, 0x5c, 0xac,
	0x75, 0x3c, 0x75, 0xad, 0xc4, 0x3b, 0xab, 0xdd, 0x75, 0x12, 0xff, 0x02, 0x27, 0x3e, 0x81, 0x4f,
	0xe0, 0xc0, 0x47, 0x20, 0x4e, 0x15, 0x27, 0x8e, 0x90, 0x1c, 0xe0, 0x33, 0xd0, 0xee, 0x3a, 0xe1,
	0x62, 0xcf, 0x7b, 0xb3, 0xf3, 0x66, 0xde, 0x23, 0x0f, 0x2b, 0x5d, 0x30, 0x2a, 0x90, 0xd1, 0xf9,
	0xb9, 0xf9, 0xc5, 0x42, 0xa2, 0x46, 0xff, 0xc0, 0xd0, 0xb1, 0xc1, 0xf3, 0xf3, 0xe1, 0xa0, 0xc4,
	0x12, 0x2d, 0x4f, 0x4d, 0xe5, 0x9e, 0x0c, 0x1f, 0x95, 0x88, 0xe5, 0x0c, 0xa8, 0x45, 0x79, 0x73,
	0x4d, 0x19, 0x6f, 0x37, 0xad, 0x09, 0xaa, 0x1a, 0x55, 0xe6, 0x66, 0x1c, 0xe8, 0x5a, 0xc7, 0xac,
	0xae, 0x38, 0x52, 0xfb, 0x75, 0xd4, 0xa9, 0x20, 0x7b, 0x09, 0x93, 0xac, 0x56, 0xfe, 0x53, 0xf2,
	0xa0, 0x66, 0xcb, 0x6c, 0xce, 0x66, 0x55, 0xc1, 0x34, 0x4a, 0x15, 0x78, 0x27, 0xde, 0x59, 0x3f,
	0xed, 0xd7, 0x6c, 0x79, 0xb5, 0x25, 0xfd, 0x27, 0xa4, 0x5f, 0xc0, 0x35, 0x6b, 0x66, 0x3a, 0x13,
	0xb8, 0x00, 0x19, 0xdc, 0x39, 0xf1, 0xce, 0x76, 0xd2, 0xfb, 0x1d, 0x99, 0x18, 0xee, 0x62, 0xf8,
	0xf7, 0xf3, 0x63, 0xef, 0xe3, 0x9f, 0x2f, 0xcf, 0x8e, 0xad, 0xc3, 0xa5, 0xf5, 0xe8, 0xf6, 0x9c,
	0xfe, 0xf6, 0xc8, 0xfe, 0x56, 0xcf, 0x7f, 0x45, 0x8e, 0x50, 0x80, 0x34, 0x75, 0xc6, 0x8a, 0x42,
	0x82, 0x72, 0x7b, 0xf7, 0xc7, 0xc1, 0x8f, 0xaf, 0xd1, 0xa0, 0x3b, 0x7f, 0xe4, 0x3a, 0x97, 0x5a,
	0x56, 0xbc, 0x4c, 0x0f, 0x37, 0x13, 0x1d, 0xed, 0xbf, 0x27, 0x47, 0x13, 0xe4, 0x0a, 0xb8, 0x6a,
	0x54, 0x26, 0x9a, 0x7c, 0x0a, 0xad, 0x3d, 0xeb, 0xe0, 0xf9, 0x20, 0x76, 0x41, 0xc5, 0x9b, 0xa0,
	0xe2, 0x11, 0x6f, 0xc7, 0xc1, 0xf7, 0xff, 0xd2, 0x13, 0xd9, 0x0a, 0x8d, 0x71, 0xd2, 0xe4, 0x6f,
	0xa1, 0x4d, 0x0f, 0xb7, 0x3a, 0x89, 0x95, 0xf1, 0x03, 0x72, 0xaf, 0x46, 0x5e, 0x4d, 0x41, 0x06,
	0x3b, 0xe6, 0xac, 0x74, 0x03, 0xfd, 0x01, 0xb9, 0xeb, 0x02, 0xd8, 0xb5, 0x01, 0x38, 0x70, 0xb1,
	0x6b, 0x9c, 0x8f, 0xaf, 0xbe, 0xad, 0x42, 0xef, 0x76, 0x15, 0x7a, 0xbf, 0x56, 0xa1, 0xf7, 0x69,
	0x1d, 0xf6, 0x6e, 0xd7, 0x61, 0xef, 0xe7, 0x3a, 0xec, 0x7d, 0x78, 0x59, 0x56, 0xfa, 0xa6, 0xc9,
	0xe3, 0x09, 0xd6, 0x54, 0x2f, 0x80, 0xeb, 0x36, 0xd2, 0x37, 0x12, 0xe0, 0x35, 0x7d, 0xa3, 0x0b,
	0x16, 0x25, 0x38, 0x8a, 0xde, 0x81, 0x5e, 0xa0, 0x9c, 0x46, 0x97, 0x20, 0xe7, 0x20, 0xbb, 0xf0,
	0x74, 0x2b, 0x40, 0xe5, 0x7b, 0xd6, 0xc6, 0x8b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x8e,
	0x8c, 0xd1, 0x39, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxValidators != that1.MaxValidators {
		return false
	}
	if this.DefaultPower != that1.DefaultPower {
		return false
	}
	return true
}
func (this *Validator) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Validator)
	if !ok {
		that2, ok := that.(Validator)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.OperatorAddress != that1.OperatorAddress {
		return false
	}
	if !this.ConsensusPubkey.Equal(that1.ConsensusPubkey) {
		return false
	}
	if this.Moniker != that1.Moniker {
		return false
	}
	if this.Power != that1.Power {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DefaultPower != 0 {
		i = encodeVarintPoa(dAtA, i, uint64(m.DefaultPower))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxValidators != 0 {
		i = encodeVarintPoa(dAtA, i, uint64(m.MaxValidators))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Validator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Power != 0 {
		i = encodeVarintPoa(dAtA, i, uint64(m.Power))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintPoa(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ConsensusPubkey != nil {
		{
			size, err := m.ConsensusPubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPoa(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintPoa(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPoa(dAtA []byte, offset int, v uint64) int {
	offset -= sovPoa(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxValidators != 0 {
		n += 1 + sovPoa(uint64(m.MaxValidators))
	}
	if m.DefaultPower != 0 {
		n += 1 + sovPoa(uint64(m.DefaultPower))
	}
	return n
}

func (m *Validator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovPoa(uint64(l))
	}
	if m.ConsensusPubkey != nil {
		l = m.ConsensusPubkey.Size()
		n += 1 + l + sovPoa(uint64(l))
	}
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovPoa(uint64(l))
	}
	if m.Power != 0 {
		n += 1 + sovPoa(uint64(m.Power))
	}
	return n
}

func sovPoa(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPoa(x uint64) (n int) {
	return sovPoa(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoa
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxValidators", wireType)
			}
			m.MaxValidators = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxValidators |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultPower", wireType)
			}
			m.DefaultPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPoa(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoa
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Validator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoa
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoa
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoa
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusPubkey == nil {
				m.ConsensusPubkey = &types.Any{}
			}
			if err := m.ConsensusPubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoa
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			m.Power = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Power |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPoa(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoa
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPoa(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPoa
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPoa
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPoa
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPoa
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPoa        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPoa          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPoa = fmt.Errorf("proto: unexpected end of group")
)
