syntax = "proto3";
package itda.payment.v1;

import "gogoproto/gogo.proto";
import "cosmos_proto/cosmos.proto";
import "amino/amino.proto";

option go_package = "github.com/twenty-threeD/Itda-PoA-Network-Server/x/payment/types";

message Params {
  option (amino.name) = "itda/x/payment/Params";
  option (gogoproto.equal) = true;
}

message PaymentRecord {
  string order_id = 1;
  string buyer_address = 2 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  int64 amount = 3;
  string paid_at = 4;
  string contract_url = 5;
  string payment_hash = 6;
  string buyer_signature = 7;
  int64 recorded_height = 8;
}
