syntax = "proto3";
package itda.payment.v1;

import "gogoproto/gogo.proto";
import "cosmos_proto/cosmos.proto";
import "cosmos/msg/v1/msg.proto";
import "amino/amino.proto";
import "itda/payment/v1/payment.proto";

option go_package = "github.com/twenty-threeD/Itda-PoA-Network-Server/x/payment/types";

service Msg {
  option (cosmos.msg.v1.service) = true;

  rpc RecordPayment(MsgRecordPayment) returns (MsgRecordPaymentResponse);
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);
}

message MsgRecordPayment {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "itda/x/payment/MsgRecordPayment";

  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string order_id = 2;
  string buyer_address = 3 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  int64 amount = 4;
  string paid_at = 5;
  string contract_url = 6;
  string payment_hash = 7;
  string buyer_signature = 8;
}

message MsgRecordPaymentResponse {
  int64 recorded_height = 1;
}

message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "itda/x/payment/MsgUpdateParams";

  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  Params params = 2 [(gogoproto.nullable) = false];
}

message MsgUpdateParamsResponse {}
