// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: itda/payment/v1/payment.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_196dbecc45daab02, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

type PaymentRecord struct {
	OrderId        string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BuyerAddress   string `protobuf:"bytes,2,opt,name=buyer_address,json=buyerAddress,proto3" json:"buyer_address,omitempty"`
	Amount         int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaidAt         string `protobuf:"bytes,4,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	ContractUrl    string `protobuf:"bytes,5,opt,name=contract_url,json=contractUrl,proto3" json:"contract_url,omitempty"`
	PaymentHash    string `protobuf:"bytes,6,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	BuyerSignature string `protobuf:"bytes,7,opt,name=buyer_signature,json=buyerSignature,proto3" json:"buyer_signature,omitempty"`
	RecordedHeight int64  `protobuf:"varint,8,opt,name=recorded_height,json=recordedHeight,proto3" json:"recorded_height,omitempty"`
}

func (m *PaymentRecord) Reset()         { *m = PaymentRecord{} }
func (m *PaymentRecord) String() string { return proto.CompactTextString(m) }
func (*PaymentRecord) ProtoMessage()    {}
func (*PaymentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_196dbecc45daab02, []int{1}
}
func (m *PaymentRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaymentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaymentRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaymentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRecord.Merge(m, src)
}
func (m *PaymentRecord) XXX_Size() int {
	return m.Size()
}
func (m *PaymentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRecord proto.InternalMessageInfo

func (m *PaymentRecord) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PaymentRecord) GetBuyerAddress() string {
	if m != nil {
		return m.BuyerAddress
	}
	return ""
}

func (m *PaymentRecord) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PaymentRecord) GetPaidAt() string {
	if m != nil {
		return m.PaidAt
	}
	return ""
}

func (m *PaymentRecord) GetContractUrl() string {
	if m != nil {
		return m.ContractUrl
	}
	return ""
}

func (m *PaymentRecord) GetPaymentHash() string {
	if m != nil {
		return m.PaymentHash
	}
	return ""
}

func (m *PaymentRecord) GetBuyerSignature() string {
	if m != nil {
		return m.BuyerSignature
	}
	return ""
}

func (m *PaymentRecord) GetRecordedHeight() int64 {
	if m != nil {
		return m.RecordedHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "itda.payment.v1.Params")
	proto.RegisterType((*PaymentRecord)(nil), "itda.payment.v1.PaymentRecord")
}

func init() { proto.RegisterFile("itda/payment/v1/payment.proto", fileDescriptor_196dbecc45daab02) }

var fileDescriptor_196dbecc45daab02 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x8a, 0xd3, 0x40,
	0x1c, 0xc7, 0x9b, 0x5d, 0x4d, 0xd7, 0x71, 0xff, 0x60, 0x58, 0x75, 0x76, 0xc1, 0xb8, 0xee, 0xc5,
	0x22, 0xa4, 0x61, 0xf1, 0x26, 0x08, 0xb6, 0x78, 0x68, 0x2f, 0x52, 0x52, 0xbc, 0xf4, 0x12, 0xa6,
	0x99, 0x21, 0x19, 0x6c, 0x32, 0xe1, 0x37, 0xbf, 0xb4, 0xe6, 0x15, 0x3c, 0xf9, 0x08, 0x3e, 0x82,
	0x88, 0x0f, 0xe1, 0xb1, 0x78, 0xf2, 0x28, 0xed, 0x41, 0x1f, 0x43, 0x32, 0x93, 0xc8, 0x5e, 0xc2,
	0x7c, 0x3f, 0x9f, 0x2f, 0xe4, 0x9b, 0x0c, 0x79, 0x22, 0x91, 0xb3, 0xb0, 0x64, 0x75, 0x2e, 0x0a,
	0x0c, 0xd7, 0x37, 0xdd, 0x71, 0x58, 0x82, 0x42, 0xe5, 0x9d, 0x35, 0x7a, 0xd8, 0xb1, 0xf5, 0xcd,
	0xe5, 0x79, 0xaa, 0x52, 0x65, 0x5c, 0xd8, 0x9c, 0x6c, 0xed, 0xf2, 0x22, 0x51, 0x3a, 0x57, 0x3a,
	0xb6, 0xc2, 0x86, 0x56, 0x3d, 0x60, 0xb9, 0x2c, 0x54, 0x68, 0x9e, 0x16, 0x5d, 0x0f, 0x88, 0x3b,
	0x63, 0xc0, 0x72, 0xfd, 0xca, 0xff, 0xfb, 0xe5, 0xa9, 0xf3, 0xe9, 0xcf, 0xd7, 0x17, 0x0f, 0xcd,
	0x8c, 0x8f, 0xff, 0x87, 0x58, 0x7f, 0xfd, 0xed, 0x80, 0x9c, 0xcc, 0x2c, 0x8a, 0x44, 0xa2, 0x80,
	0x7b, 0x17, 0xe4, 0x48, 0x01, 0x17, 0x10, 0x4b, 0x4e, 0x9d, 0x2b, 0x67, 0x70, 0x2f, 0xea, 0x9b,
	0x3c, 0xe5, 0xde, 0x6b, 0x72, 0xb2, 0xac, 0x6a, 0x01, 0x31, 0xe3, 0x1c, 0x84, 0xd6, 0xf4, 0xa0,
	0xf1, 0x63, 0xfa, 0xf3, 0x7b, 0x70, 0xde, 0x4e, 0x1a, 0x59, 0x33, 0x47, 0x90, 0x45, 0x1a, 0x1d,
	0x9b, 0x7a, 0xcb, 0xbc, 0x47, 0xc4, 0x65, 0xb9, 0xaa, 0x0a, 0xa4, 0x87, 0x57, 0xce, 0xe0, 0x30,
	0x6a, 0x93, 0xf7, 0x98, 0xf4, 0x4b, 0x26, 0x79, 0xcc, 0x90, 0xde, 0x31, 0x2f, 0x74, 0x9b, 0x38,
	0x42, 0xef, 0x19, 0x39, 0x4e, 0x54, 0x81, 0xc0, 0x12, 0x8c, 0x2b, 0x58, 0xd1, 0xbb, 0xc6, 0xde,
	0xef, 0xd8, 0x7b, 0x58, 0x35, 0x95, 0xf6, 0x8b, 0xe2, 0x8c, 0xe9, 0x8c, 0xba, 0xb6, 0xd2, 0xb2,
	0x09, 0xd3, 0x99, 0xf7, 0x9c, 0x9c, 0xd9, 0xd5, 0x5a, 0xa6, 0x05, 0xc3, 0x0a, 0x04, 0xed, 0x9b,
	0xd6, 0xa9, 0xc1, 0xf3, 0x8e, 0x36, 0x45, 0x30, 0xff, 0x40, 0xf0, 0x38, 0x13, 0x32, 0xcd, 0x90,
	0x1e, 0x99, 0xa1, 0xa7, 0x1d, 0x9e, 0x18, 0x3a, 0x5e, 0xfc, 0xd8, 0xf9, 0xce, 0x76, 0xe7, 0x3b,
	0xbf, 0x77, 0xbe, 0xf3, 0x79, 0xef, 0xf7, 0xb6, 0x7b, 0xbf, 0xf7, 0x6b, 0xef, 0xf7, 0x16, 0x6f,
	0x52, 0x89, 0x59, 0xb5, 0x1c, 0x26, 0x2a, 0x0f, 0x71, 0x23, 0x0a, 0xac, 0x03, 0xcc, 0x40, 0x88,
	0xb7, 0xe1, 0x14, 0x39, 0x0b, 0x66, 0x6a, 0x14, 0xbc, 0x13, 0xb8, 0x51, 0xf0, 0x21, 0x98, 0x0b,
	0x58, 0x0b, 0xb8, 0x75, 0x23, 0x58, 0x97, 0x42, 0x2f, 0x5d, 0x73, 0x83, 0x2f, 0xff, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xe6, 0xa2, 0xae, 0xc2, 0x37, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *PaymentRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaymentRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RecordedHeight != 0 {
		i = encodeVarintPayment(dAtA, i, uint64(m.RecordedHeight))
		i--
		dAtA[i] = 0x40
	}
	if len(m.BuyerSignature) > 0 {
		i -= len(m.BuyerSignature)
		copy(dAtA[i:], m.BuyerSignature)
		i = encodeVarintPayment(dAtA, i, uint64(len(m.BuyerSignature)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.PaymentHash) > 0 {
		i -= len(m.PaymentHash)
		copy(dAtA[i:], m.PaymentHash)
		i = encodeVarintPayment(dAtA, i, uint64(len(m.PaymentHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ContractUrl) > 0 {
		i -= len(m.ContractUrl)
		copy(dAtA[i:], m.ContractUrl)
		i = encodeVarintPayment(dAtA, i, uint64(len(m.ContractUrl)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PaidAt) > 0 {
		i -= len(m.PaidAt)
		copy(dAtA[i:], m.PaidAt)
		i = encodeVarintPayment(dAtA, i, uint64(len(m.PaidAt)))
		i--
		dAtA[i] = 0x22
	}
	if m.Amount != 0 {
		i = encodeVarintPayment(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.BuyerAddress) > 0 {
		i -= len(m.BuyerAddress)
		copy(dAtA[i:], m.BuyerAddress)
		i = encodeVarintPayment(dAtA, i, uint64(len(m.BuyerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrderId) > 0 {
		i -= len(m.OrderId)
		copy(dAtA[i:], m.OrderId)
		i = encodeVarintPayment(dAtA, i, uint64(len(m.OrderId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPayment(dAtA []byte, offset int, v uint64) int {
	offset -= sovPayment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *PaymentRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderId)
	if l > 0 {
		n += 1 + l + sovPayment(uint64(l))
	}
	l = len(m.BuyerAddress)
	if l > 0 {
		n += 1 + l + sovPayment(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovPayment(uint64(m.Amount))
	}
	l = len(m.PaidAt)
	if l > 0 {
		n += 1 + l + sovPayment(uint64(l))
	}
	l = len(m.ContractUrl)
	if l > 0 {
		n += 1 + l + sovPayment(uint64(l))
	}
	l = len(m.PaymentHash)
	if l > 0 {
		n += 1 + l + sovPayment(uint64(l))
	}
	l = len(m.BuyerSignature)
	if l > 0 {
		n += 1 + l + sovPayment(uint64(l))
	}
	if m.RecordedHeight != 0 {
		n += 1 + sovPayment(uint64(m.RecordedHeight))
	}
	return n
}

func sovPayment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPayment(x uint64) (n int) {
	return sovPayment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPayment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPayment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPayment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PaymentRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPayment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaymentRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaymentRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPayment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPayment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPayment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPayment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaidAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPayment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPayment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaidAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPayment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPayment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPayment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPayment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerSignature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPayment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPayment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyerSignature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordedHeight", wireType)
			}
			m.RecordedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPayment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPayment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPayment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPayment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPayment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPayment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPayment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPayment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPayment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPayment = fmt.Errorf("proto: unexpected end of group")
)
